version: "3.8"

services:
  db:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "dba"
      MYSQL_PASSWORD: "dba"
    volumes:
      - ./data/db:/var/lib/mysql

  app:
    image: python:3.10
    working_dir: /src
    command: make run
    volumes:
      - $PWD/src:/src/
